spring:
  application:
    name: cps-spring-cloud-zuul
server:
  port: 8040
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka
  instance:
    prefer-ip-address: true
#zuul:
#  routes:
#    cps_user: /user/**
#    cps_photo: /photo/**
#    cps_comment: /comment/**
#  instance:
#    prefer-ip-address: true 
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
zuul:
  routes:
    abc:
      path: /photo/**
      service-id: cps_photo
  ignore-security-headers: false
ribbon:
  eureka:
    enabled: false
  ConnectTimeout: 3000
  ReadTimeout: 60000
cps_photo:     # 这边是ribbon要请求的微服务的serviceId
  ribbon:
    listOfServers: http://localhost:8081,http://localhost:8083
    
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000

